openapi: "3.0.2"
info:
  title: Open BBS API
  version: "0.1"
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    TopicCategory:
      type: object
      properties:
        id:
          type: integer
          description: カテゴリーID
        name:
          type: string
          description: カテゴリー名
    TopicCategories:
      type: array
      items:
        $ref: "#/components/schemas/TopicCategory"
paths:
  /api/topic-categories:
    get:
      summary: トピックカテゴリー一覧を取得する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicCategories"

